default_language_version:
  python: python3.6
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: seed-isort-config
        name: seed-isort-config
        entry: seed-isort-config
        require_serial: true
        language: python
        always_run: true
        pass_filenames: false
    -   id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]
    -   id: black
        name: black
        entry: black
        require_serial: true
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        require_serial: true
        language: python
        types: [python]
